### ISSUE TITLE
问题反馈：会把未来的文章也输出出来

### ISSUE THREAD

**Issue by htmlwebsites** [invelop/Typecho-HPSitemap#1]
首先感谢开发、优化这么好的插件！

有个小问题，如果文章设定日期在未来，插件仍然会在sitemap中输出，而实际该文章访问是404的。
即，如果有篇文章我提前写好，但我不想现在发出来，想在以后发出来，比如在2020年元旦，我只需要把日期设置在元旦即可，这样网站中这篇文章不会显现出来；但插件生成的sitemap中，仍会把这篇文章列出，如果蜘蛛按照这个sitemap文件过来，访问那篇文章会显示404，可能会有影响，希望能再改进、优化，再次感谢！

**Comment by p0ise** [comment]
目前已经修复了，感谢反馈！
